### ISSUE TITLE
Add posibility to add custom class next to tooltipstered

### ISSUE THREAD

**Issue by pacocom** [jamiees2/react-tooltipster#2]
Add posibility to add custom class next to tooltipstered

`<span class="tooltipstered CUSTOM-CLASS">content</span>`

Thank

**Comment by jamiees2** [comment]
Sorry for the late response, but I think you could do this with the `rootProps` argument, for example here: https://github.com/jamiees2/react-tooltipster/blob/0997ba3648443486271de46459522db90b52a3cf/demo/index.js#L15
